codecov:
  notify:
    require_ci_to_pass: true

comment: off

coverage:
  precision: 0
  range:
  - 50.0
  - 100.0
  round: down
  status:
    changes: false
    patch: false
    project: false

parsers:
  gcov:
    branch_detection:
      conditional: true
      loop: true
      macro: false
      method: false
